### ISSUE TITLE
RuntimeError: abort(OOM). Build with -s ASSERTIONS=1 for more info.

### ISSUE THREAD

**Issue by think-hash** [indix/kafkajs-lz4#15]
OOM
RuntimeError: abort(OOM). Build with -s ASSERTIONS=1 for more info.
    at y (D:\LTXY\services\hainan\kafka_to_databus\node_modules\lz4-asm\dist\lz4wasm.js:16:393)
    at c (D:\LTXY\services\hainan\kafka_to_databus\node_modules\lz4-asm\dist\lz4wasm.js:19:185)
    at <anonymous>:wasm-function[8]:0x2393
    at <anonymous>:wasm-function[6]:0x139d
    at <anonymous>:wasm-function[37]:0x11419
    at m (<anonymous>:wasm-function[58]:0x15c37)
    at b.L (D:\LTXY\services\hainan\kafka_to_databus\node_modules\lz4-asm\dist\lz4wasm.js:36:268)
    at b.K (D:\LTXY\services\hainan\kafka_to_databus\node_modules\lz4-asm\dist\lz4wasm.js:36:340)
    at Object.decompress (D:\LTXY\services\hainan\kafka_to_databus\node_modules\lz4-asm\dist\lz4wasm.js:41:180)
    at D:\LTXY\services\hainan\kafka_to_databus\node_modules\kafkajs-lz4\lib\index.js:37:50

**Comment by paambaati** [comment]
This looks like an upstream issue; you'd have better luck raising this issue in the https://www.npmjs.com/package/lz4-asm issue tracker.
