### ISSUE TITLE
yarn add kafkajs-lz4 issue

### ISSUE THREAD

**Issue by Mickael-M** [indix/kafkajs-lz4#5]
Hello everyone,

I end up with this issue when trying install kafkajs-lz4:
```
Debugger listening on ws://127.0.0.1:35199/f902c608-883d-4c84-963a-d05c60fb4e8c
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
yarn add v1.22.5
warning ../../package.json: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/mickael/certificate/kafkaConnection/node_modules/lz4: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/mickael/certificate/kafkaConnection/node_modules/lz4
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@12.18.4 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python2"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/mickael/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mickael/certificate/kafkaConnection/node_modules/lz4/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mickael/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/mickael/.cache/node-gyp/12.18.4/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/mickael/.cache/node-gyp/12.18.4',
gyp info spawn args   '-Dnode_gyp_dir=/home/mickael/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/mickael/.cache/node-gyp/12.18.4/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/mickael/certificate/kafkaConnection/node_modules/lz4',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Debugger listening on ws://127.0.0.1:42773/b91d4216-5886-4dc8-a6be-86c4cb20d334
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Waiting for the debugger to disconnect...
gyp: Call to 'node -e "require('nan')"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/mickael/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.0-48-generic
gyp ERR! command "/home/mickael/.nvm/versions/node/v12.18.4/bin/node" "/home/mickael/.nvm/versions/node/v12.18.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mickael/certificate/kafkaConnection/node_modules/lz4
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
```
Did anyone face this issue?
Is there a way to work around it?
Thanks in advance for your answers

**Comment by paambaati** [comment]
The trace shows debugger running. It isn’t supposed to do that when you run the `yarn` command.

Can you share your `package.json` and ensure you’re running `yarn install` from the same directory as `package.json`?
